### ISSUE TITLE
Win10 build 19042

### ISSUE THREAD

**Issue by ErwinMeulman** [GaelGirodon/Tile#1]
Is not working

**Comment by GaelGirodon** [comment]
I just tested it on Windows 10 20H2 (build 19042.928) with .NET Framework 4.8.04084 and it is working fine, could you provide more details about your issue?

![tile](https://user-images.githubusercontent.com/10748287/115972282-b43ea000-a54d-11eb-963a-eab51226a798.png)

**Comment by ErwinMeulman** [comment]
I am sorry, I was wrong
